[__config__]
oldver = "repo_packages.txt"
newver = "nvchecker_packages.json"

[alsa-ucm-conf]
source = "git"
git = "git://git.alsa-project.org/alsa-ucm-conf"

[anx7688-firmware]
source = "git"
git = "https://xff.cz/git/linux-firmware"
use_commit = true

[autocutsel]
source = "github"
github = "sigmike/autocutsel"
use_max_tag = true

[bes2600-firmware]
source = "git"
git = "https://gitlab.com/pine64-org/bes2600-firmware.git"
use_commit = true

[brcm-firmware]
source = "git"
git = "https://xff.cz/git/linux-firmware"
use_commit = true

[clickclack]
source = "git"
git = "https://git.sr.ht/~proycon/clickclack"

[codemadness-frontends]
source = "git"
git = "git://git.codemadness.org/frontends"

[hfd-service]
source = "git"
git = "https://gitlab.com/ubports/core/hfd-service.git"

[linux-megi]
source = "git"
git = "https://codeberg.org/megi/linux.git"

[linux-pinetab2]
source = "git"
git = "https://github.com/dreemurrs-embedded/linux-pinetab2"
include_regex = '.*-danctnix.*'
from_pattern = "-danctnix"
to_pattern = ".danctnix"
prefix = "v"

[lisgd]
source = "git"
git = "https://git.sr.ht/~mil/lisgd"

[lomiri-deviceinfo]
source = "git"
git = "https://gitlab.com/ubports/development/core/deviceinfo.git"

[mnc]
source = "git"
git = "https://git.sr.ht/~anjan/mnc"

[modemmanager]
source = "git"
git = "https://gitlab.freedesktop.org/mobile-broadband/ModemManager.git"
exclude_regex = ".*-dev"

[ov5640-firmware]
source = "git"
git = "https://github.com/pmsourcedump/ov5640.git"
use_commit = true

[plasma-dialer]
source = "git"
git = "https://invent.kde.org/plasma-mobile/plasma-dialer.git"
prefix = "v"

[plasma-mobile]
source = "git"
git = "https://invent.kde.org/plasma/plasma-mobile.git"
prefix = "v"

[plasma-mobile-sounds]
source = "git"
git = "https://invent.kde.org/plasma-mobile/plasma-mobile-sounds.git"
prefix = "v"

[plasma-nano]
source = "git"
git = "https://invent.kde.org/plasma/plasma-nano.git"
prefix = "v"

[plasma-phone-settings]
source = "git"
git = "https://invent.kde.org/plasma-mobile/plasma-phone-settings.git"
use_commit = true
branch = "master"

[plasma-phonebook]
source = "git"
git = "https://invent.kde.org/plasma-mobile/plasma-phonebook.git"
prefix = "v"

[plasma-settings]
source = "git"
git = "https://invent.kde.org/plasma-mobile/plasma-settings.git"
prefix = "v"

[pnc]
source = "git"
git = "https://git.sr.ht/~anjan/pnc"

[ppkb-tools]
source = "git"
git = "https://xff.cz/git/pinephone-keyboard"

[sfeed]
source = "git"
git = "git://git.codemadness.org/sfeed"

[spacebar]
source = "git"
git = "https://invent.kde.org/plasma-mobile/spacebar.git"
prefix = "v"

[superd]
source = "git"
git = "https://git.sr.ht/~craftyguy/superd"

[svkbd]
source = "git"
git = "https://git.suckless.org/svkbd"

[sxmo-dmenu]
source = "git"
git = "https://git.sr.ht/~mil/sxmo-dmenu"

[sxmo-dwm]
source = "git"
git = "https://git.sr.ht/~mil/sxmo-dwm"

[sxmo-st]
source = "git"
git = "https://git.sr.ht/~mil/sxmo-st"

[sxmo-surf]
source = "git"
git = "https://git.sr.ht/~mil/sxmo-surf"

[sxmo-utils]
source = "git"
git = "https://git.sr.ht/~mil/sxmo-utils"

[tinydm]
source = "git"
git = "https://gitlab.com/postmarketOS/tinydm.git"

[wayout]
source = "git"
git = "https://git.sr.ht/~proycon/wayout"

[wvkbd]
source = "git"
git = "https://git.sr.ht/~proycon/wvkbd"
prefix = "v"

[xob]
source = "github"
github = "florentc/xob"
use_max_tag = true
prefix = "v"
